# Generated by Django 3.2.16 on 2023-01-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('WORLD', 'World'), ('BUSINESS', 'Business'), ('FOOD', 'Food'), ('CULTURE', 'Culture'), ('MUSIC', 'Music'), ('TECH', 'Tech')], default='WORLD', max_length=8),
        ),
    ]
